# Generated by Django 4.0.3 on 2022-05-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='identificador',
            field=models.CharField(default='key_dbmovie', max_length=100, unique=True),
        ),
    ]
